---
jobs:
- name: test-concourse-broker
  plan:
  - get: broker-src
    trigger: true
  - task: run-tests
    file: broker-src/ci/run-tests.yml

- name: push-concourse-broker-staging
  serial_groups: [staging]
  serial: true
  plan:
  - aggregate:
    - get: broker-src
      passed: [test-concourse-broker]
      trigger: true
  - put: broker-deploy-staging
    params:
      path: broker-src
      manifest: broker-src/manifest.yml
      environment_variables:
        BROKER_USERNAME: {{broker-username-staging}}
        BROKER_PASSWORD: {{broker-password-staging}}
        ADMIN_USERNAME: {{concourse-username-staging}}
        ADMIN_PASSWORD: {{concourse-password-staging}}
        CONCOURSE_URL: {{concourse-url-staging}}
        CF_URL: {{cf-api-url-staging}}
        AUTH_URL: {{auth-url-staging}}
        TOKEN_URL: {{token-url-staging}}
        CLIENT_ID: {{client-id-staging}}
        CLIENT_SECRET: {{client-secret-staging}}
  - task: update-broker
    file: broker-src/ci/register-service-broker.yml
    params:
      CF_API_URL: {{cf-api-url-staging}}
      CF_USERNAME: {{cf-deploy-username-staging}}
      CF_PASSWORD: {{cf-deploy-password-staging}}
      CF_ORGANIZATION: {{cf-organization-staging}}
      CF_SPACE: {{cf-space-staging}}
      BROKER_NAME: concourse-broker
      AUTH_USER: {{broker-username-staging}}
      AUTH_PASS: {{broker-password-staging}}
      SERVICES: concourse-ci

- name: concourse-broker-acceptance-tests-staging
  serial_groups: [staging]
  serial: true
  plan:
  - get: broker-src
    passed: [push-concourse-broker-staging]
    trigger: true
  - task: acceptance-tests-staging
    file: broker-src/ci/acceptance-tests.yml
    params:
      CF_API_URL: {{cf-api-url-staging}}
      CF_USERNAME: {{cf-deploy-username-staging}}
      CF_PASSWORD: {{cf-deploy-password-staging}}
      CF_ORGANIZATION: {{cf-organization-staging}}
      CF_SPACE: {{cf-space-staging}}
      PLAN_NAME: concourse-ci
      SERVICE_INSTANCE_NAME: concourse-ci-acceptance
      CONCOURSE_URL: {{concourse-url-staging}}

resources:
- name: broker-src
  type: git
  source:
    uri: {{concourse-broker-git-url}}
    branch: {{concourse-broker-git-branch}}

- name: broker-deploy-staging
  type: cf
  source:
    api: {{cf-api-url-staging}}
    username: {{cf-deploy-username-staging}}
    password: {{cf-deploy-password-staging}}
    organization: {{cf-organization-staging}}
    space: {{cf-space-staging}}
